### ISSUE TITLE
Create post (take photo) back button causes crash 

### ISSUE THREAD

**Issue by SamHammersley** [cupcaketees/CupCakeTees#30]
@HugoCSWork 
Related to extras in an intent.

# Recreation:

1. Navigate to posts activity via navigation bar
2. Press the photo button on the bottom bar
3. Press open camera button
4. Press back on the camera activity

# Stack trace
`java.lang.NullPointerException:Attempt to invoke virtual method 'android.os.Bundle android.content.Intent.getExtras()' on a null object reference`

**Comment by HugoCSWork** [comment]
Problem has been resolved and will be pushed in the next commit.
